# Generated by Django 4.2.7 on 2023-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cursus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etablissement", models.CharField(max_length=200, null=True)),
                ("diplome_name", models.CharField(max_length=200, null=True)),
                ("anneedebut", models.DateField(null=True)),
                ("anneeFin", models.DateField(null=True)),
            ],
        ),
    ]
