# Generated by Django 3.2.6 on 2023-12-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etudiants', '0001_initial'),
        ('Cursus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.etudiant'),
        ),
    ]
