# Generated by Django 3.2.6 on 2023-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursus', '0004_auto_20231204_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='cycle',
            field=models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=200, null=True),
        ),
    ]
