# Generated by Django 3.2.6 on 2023-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursus', '0005_cursus_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='autre_cycle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cursus',
            name='cycle',
            field=models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('Autre', 'Autre')], max_length=200, null=True),
        ),
    ]
