# Generated by Django 3.2.6 on 2023-12-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursus', '0006_auto_20231205_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='autre_cycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
