# Generated by Django 4.2.7 on 2023-11-16 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Emploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entreprise", models.CharField(max_length=200, null=True)),
                ("typecont", models.CharField(max_length=200, null=True)),
                ("poste", models.CharField(max_length=200, null=True)),
                ("anneedebut", models.DateField(null=True)),
                ("anneeFin", models.DateField(null=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
