# Generated by Django 3.2.6 on 2023-11-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
