# Generated by Django 3.2.6 on 2023-11-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emploi', '0002_emploi_etudiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploi',
            old_name='anneedatedebut',
            new_name='annee_date_debut',
        ),
        migrations.RenameField(
            model_name='emploi',
            old_name='anneedatefin',
            new_name='annee_date_fin',
        ),
        migrations.RenameField(
            model_name='emploi',
            old_name='moisdatedebut',
            new_name='mois_date_debut',
        ),
        migrations.RenameField(
            model_name='emploi',
            old_name='moisdatefin',
            new_name='mois_date_fin',
        ),
    ]
