# Generated by Django 3.2.6 on 2023-12-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('pourcentage', models.FloatField(max_length=65, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.etudiant')),
            ],
        ),
    ]
