# Generated by Django 3.2.6 on 2023-11-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_auto_20231117_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='pourcentage',
            field=models.FloatField(max_length=65, null=True),
        ),
    ]
