# Generated by Django 3.2.6 on 2023-12-19 15:58

import Etudiants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code_permenant', models.CharField(max_length=200, null=True, unique=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('tel', models.CharField(max_length=200, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('niveau_actuel', models.CharField(max_length=200, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to=Etudiants.models.upload_to)),
                ('about', models.TextField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Users.user',),
        ),
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ImageField(blank=True, null=True, upload_to=Etudiants.models.upload_photo_profile)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCouverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to=Etudiants.models.upload_photo_couverture)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiants.etudiant')),
            ],
        ),
    ]
