# Generated by Django 4.2.7 on 2023-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Etudiants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="username",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
