# Generated by Django 3.2.6 on 2023-12-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='photo_couverture/'),
        ),
    ]
