# Generated by Django 3.2.6 on 2023-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0002_alter_etudiant_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau_actuel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
