# Generated by Django 3.2.6 on 2023-12-09 16:13

import Etudiants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0003_etudiant_niveau_actuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to=Etudiants.models.upload_to),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=Etudiants.models.upload_to),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Etudiants.models.upload_to),
        ),
    ]
