# Generated by Django 3.2.6 on 2023-12-09 17:42

import Etudiants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0004_auto_20231209_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='couverture',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='photo',
        ),
        migrations.CreateModel(
            name='PhotoProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ImageField(blank=True, null=True, upload_to=Etudiants.models.upload_photo_profile)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCouverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.ImageField(blank=True, null=True, upload_to=Etudiants.models.upload_photo_couverture)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
